# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Fortuna' do
    pod 'Alamofire'
    pod 'AFNetworking'
    
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    
    #pod 'SDWebImage'
    
    pod 'SnapKit'
    pod 'Masonry'
    
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxAlamofire'
    pod 'Moya/RxSwift'
    #pod 'Moya'
    
    #蓝牙
    #pod 'MPBluetoothKit'
    
    #高度自适应
    #pod 'UITableView+FDTemplateLayoutCell'
    
    #图表库
    pod 'Charts'
    
    #pod 'Hyphenate_CN'
    
    pod 'MJRefresh'
    
    #pod 'YYKit'
    #pod 'YYModel'
    #pod 'YYWebImage'
    pod 'YYCache'
    pod 'YYImage'
    pod 'YYWebImage'
    pod 'YYText'
    pod 'YYKeyboardManager'
    pod 'YYDispatchQueuePool'
    pod 'YYAsyncLayer'
    pod 'YYCategories'
    
    pod 'IQKeyboardManager'
    
    pod 'WebViewJavascriptBridge'
    pod 'IMYWebView'
    
    pod 'DZNEmptyDataSet'
    pod 'CYLTableViewPlaceHolder'
    
    # 即时通讯组件
    pod 'Socket.IO-Client-Swift'
    
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'
    
    # 集成微信(精简版0.2M)
    pod 'UMengUShare/Social/ReducedWeChat'
    
    # 集成微信(完整版14.4M)
    #pod 'UMengUShare/Social/WeChat'
    
    # 集成QQ(精简版0.5M)
    pod 'UMengUShare/Social/ReducedQQ'
    
    # 集成QQ(完整版7.6M)
    #pod 'UMengUShare/Social/QQ'
    
    # 集成新浪微博(精简版1M)
    pod 'UMengUShare/Social/ReducedSina'
    
    # 集成新浪微博(完整版25.3M)
    #pod 'UMengUShare/Social/Sina'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
